version: '2'
services:
 master:
   image: bitnami/spark:2.3.1
   ports:
    - "8080:8080"
    - "7077:7077"
    - "6066:6066"
restart: always
 slave:
   command: "slave spark://master:7077"
   image: bitnami/spark:2.3.1
   depends_on:
    - master
   ports:
    - "8081:8081"
restart: always
